Dev
sandy-git-only/remote-assignments pull request #1
Opened 2023-09-29 16:56 UTC by sandy-git-only

Elastic IP address : 46.51.228.163
Database name : database-1.cpkgs4mvvlco.ap-northeast-1.rds.amazonaws.com
Change summary : 
- Add Readme.md
- Upload requestSync.js and requestAsync.js
- Create dev. branch

## Assignment 1
Connected successfully
![螢幕擷取畫面 2023-09-29 235200](https://github.com/sandy-git-only/remote-assignments/assets/138612845/40030eef-d8d1-4715-ab94-7d209429c81e)

### Understanding Check
1. How do you make sure that you can connect into your RDS? And please post the successfully
connected screen shot.
- 根據官方提供的指示，在terminal顯示的介面與官方指示相同，會顯示:"Welcome to the MySQL monitor......"訊息
2. Without Elastic IP, if we stop the EC2 instance and start it again, would the IP address change? Why?
- 如果沒有設定Elastic IP，我們將EC2 instance 停止後再啟動，其IP address可能會改變，因為在原先EC2預設的IP位址屬於動態IP address分配，假如停止了我們的EC2，系統便會將原本EC2的IP address釋放出來。
3. What's the purpose of using Elastic IP?
- 使用Elastic IP 也就是固定的IP address，因此即使停止了instance後再開啟，也不會造成IP address改變，而產生連結問題。

## Assignment 3 
![螢幕擷取畫面 2023-09-29 215639](https://github.com/sandy-git-only/remote-assignments/assets/138612845/22f88089-a985-4a50-bb71-262f5793e588)
![螢幕擷取畫面 2023-09-29 235603](https://github.com/sandy-git-only/remote-assignments/assets/138612845/9f7438d8-5f54-482a-90df-edfd3cb41206)
_**observations**_

### 1. Based on the result of experiment, what's the differences of sync/async functions we can tell?
- 採用Async functions 的執行時間會比 Sync functions的時間短，且進行Async functions時，在送出請求後就會直接執行其他code部分，等到請求回傳response，再進行下一步處理，而Sync functions則是每一步都須等Request得到response，才進行下一步。

### 2. In which types of situations are asynchronous functions most useful?
- Async functions 用在等待讀取檔案、等待外部server或API回應請求...等時特別有用，等待的時間中，可以先處理code其他部分。

### 3. We've known the 3 ways to implement async functions, how do we choose from them and what are their pros and cons?
1. requestCallback
- pros : 簡單、直覺，適合用在只需要處理一個callback function時
- cons : 不適合用在有多個async request的時候，除了callback function串接上可能會有語法不一致的問題，code也會像巢狀一樣，多層的包裹，使code不易讀，在處理error時也會變得複雜，難以維護。

2. requestPromise
- pros: 易於使用，promise會回傳resolve成功與reject錯誤的訊息，也可透過.then()、.catch()簡單連接多個request，在code的可讀性較callback functions好。
- cons: 如果有多個promise，就會讓code看起來複雜難以閱讀，處理錯誤也難以找出是哪個promise的步驟有問題。

3. requestAsyncAwait
- pros: async/await也稱為的語法糖衣，code的可讀性是三者中最好的，可以將promise儲存在一個variable中，後面方便調用，在語法上更接近同步處理的方式，寫起來更為直覺且易懂，結合try...catch，可以更容易發現error並處理。
- cons: 由於需等每個await一一處理完後才會往下逐一執行，可能會造成效率不高。

4. Any other observations
- 由於我在每個function中皆加入時間計算的方法，而requestAsyncAwait function中有 await requestPromise function，從terminal中print出的訊息可以發現，Async/await只是個處理Async request的方法，因此執行時間為0~1ms，也就是與執行此function幾乎同步，主要的執行時間是花在等待requestPromise處理完請求。
- node.js 不支援 xhr.open中同步請求的處理，所以在requestSync.js 中使用axios來模擬synchronous request。

2023-09-30 10:00 UTC, addie-tyc requested changes
requestSync 的寫法可能需要調整，另外，需要去計算兩個檔案的執行總時間喔！像範例的截圖那樣

2023-09-30 13:47 UTC, sandy-git-only commented
> assignement 3 需要去計算兩個檔案的執行總時間喔！像範例的截圖那樣

我有再嘗試修改了一下requestSync.js

```
const url = "https://ec2-54-64-246-136.ap-northeast-1.compute.amazonaws.com/delay-clock";

function requestSync(url){
    const startTime = new Date().getTime();
    const request = require('sync-request');
    const response = request('GET', url);

    if (response.statusCode === 200) {
        const data = JSON.parse(response.getBody('utf8'));
        console.log(data);
        } else {
        console.error(`A network error occurred: ${response.statusCode}`);
    }
    const endTime = new Date().getTime();
    const executionTime = endTime - startTime;
    console.log(`Synchronous requestCallback execution time: ${executionTime} ms`)
}

requestSync(url) // would print out the execution time
requestSync(url)
requestSync(url)
```
這邊透過"sync-request"實現，因此在terminal印出網頁訊息時，可以發現是根據requestSync(url)一次一次打印出來，最後總執行時間是三次request相加的結果，而非像Async request一樣最後幾乎同步打印出來，總執行時間與三個function各自處理時間幾乎相同。另外也附上requestSync.js和requestAsync.js的執行總時間截圖。
[requestSync.js]
![螢幕擷取畫面 2023-09-30 212632](https://github.com/sandy-git-only/remote-assignments/assets/138612845/d1d3f75d-7fcb-4ab5-9ede-5f73c4465781)
[requestAsync.js]
![螢幕擷取畫面 2023-09-30 212625](https://github.com/sandy-git-only/remote-assignments/assets/138612845/2514f9fc-e284-49ac-a4f5-897c99f57dbd)

2023-10-01 16:23 UTC, addie-tyc approved these changes
LGTM

2023-10-08 12:30 UTC, sandy-git-only commented
- IP address can access to your APIs : http://46.51.228.163:3000/users
- Database name : assignment

### Change summary:
1. How did you design the user table schema? Why?
使用Myworkbench，依照指示建立assignment (database)，user (table)，datatime採用DATETIME格式，id用command的方式設定為自動新增ALTER TABLE `user` MODIFY COLUMN `id` INT AUTO_INCREMENT(因為一開始建立無法選擇Auto_increment的選項)
  
2. What does the status code mean? Is it a must to use?
status code 可以確認目前程式是否為正常運行，若有錯誤，可以依照設定的錯誤代碼返回錯誤訊息，方便之後debug
  
3. How and what tools did you use to test your APIs?
我使用Postman，介面操作簡單，可以選擇要發出GET還是POST請求，並能馬上得到response及error訊息
  
4. How and what tools did you use to make sure the app would not shut down even if you exit the ssh connection?
我使用forever這個工具  (npm install -g forever)
  
5. What are the interactions between client, firewall, EC2 and RDS when you send a request to your app server and get the response? You can use sequence diagram to describe it more clearly.
![螢幕擷取畫面 2023-10-08 201814](https://github.com/sandy-git-only/remote-assignments/assets/138612845/09f0fca5-2023-4c31-a40b-ab97dba454d0)

2023-10-08 15:05 UTC, addie-tyc commented
1. 一開始建立的時候應該就可以指定 `AUTO_INCREMENT` 囉
2. 可以再多描述一下如何確認是否正常運行？比較方便 debug 是方便在哪裡？是否必須使用呢？

2023-10-08 15:08 UTC, addie-tyc requested changes

2023-10-08 15:08 UTC, addie-tyc commented on app.js
> +const bodyParser = require('body-parser');
Express 4.18 仍然需要 bodyParser 嗎？

2023-10-08 15:08 UTC, addie-tyc commented on app.js
> +
Express 是由上到下作 endpoint 的解析，因為你的 /users 會直接回一個字串，所以現在 User query API 是沒辦法使用的喔！
<img width="1004" alt="截圖 2023-10-08 23 03 17" src="https://github.com/sandy-git-only/remote-assignments/assets/65952631/c3a2c935-3633-412e-a1ff-33688d59bc89">

2023-10-08 15:08 UTC, addie-tyc commented on app.js
> +        'request-date': new Date().toUTCString(),
request-date 直接從 client 的 request headers 裡面拿來回覆就可以了

2023-10-08 15:08 UTC, addie-tyc commented on app.js
> +          'request-date': signupTime,  // Get the current UTC date and time
同上

2023-10-08 15:49 UTC, sandy-git-only commented on app.js
> +
已修改~

2023-10-08 15:50 UTC, sandy-git-only commented on app.js
> +const bodyParser = require('body-parser');
找了資料，發現4.16之後就不需要了，因此改成
```
const express = require('express');
const mysql = require('mysql2');
const app = express();
app.use(express.json())
```

2023-10-08 16:03 UTC, sandy-git-only commented
> 1. 一開始建立的時候應該就可以指定 `AUTO_INCREMENT` 囉
因為一開始建立的時候Auto Increment是無法選擇的，所以我以為是需要後來才能改動，還是我哪裡漏掉了呢
![螢幕擷取畫面 2023-10-08 235224](https://github.com/sandy-git-only/remote-assignments/assets/138612845/5c53da11-6e38-490d-b5e8-204a94527721)

> 2. 可以再多描述一下如何確認是否正常運行？比較方便 debug 是方便在哪裡？是否必須使用呢？
status code = 200 代表能正確接收請求的資料、處理，並成功回傳，方便debug是因為這些代碼為HTTP對於為公開的協定，用來表示對請求給予的回應，所以可以針對某些error事先寫好，如果發生某類的請求錯誤就能較快看出是code哪部分有問題，可以方便debug，有助於效率和網頁維護，但這在寫網頁中並非為必要部分。

2023-10-08 16:22 UTC, sandy-git-only commented on app.js
> +        'request-date': new Date().toUTCString(),
將requestDate修改成：
`const requestDate = req.get('Date')`

2023-10-09 04:21 UTC, addie-tyc commented on app.js
> +        'request-date': new Date().toUTCString(),
差一點點，是客製化的 header `Request-Date` XD

2023-10-09 04:23 UTC, addie-tyc commented
喔，原來是 GUI 啊，這個我就不確定了，但如果是用 SQL 指令的話是可以在 create 的時候就指定

2023-10-09 04:24 UTC, addie-tyc requested changes
記得把改動的部分也 push 上來喔，現在好像還沒看到新的 commit？

2023-10-09 13:40 UTC, sandy-git-only commented
> 記得把改動的部分也 push 上來喔，現在好像還沒看到新的 commit？

Push上來了～

2023-10-09 15:12 UTC, sandy-git-only commented on app.js
> +        'request-date': new Date().toUTCString(),
修改好了～～～

2023-10-09 15:48 UTC, addie-tyc approved these changes
LGTM

2023-10-13 04:40 UTC, closed without merging